# Generated by Django 2.2.3 on 2019-07-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=100)),
                ('sexo', models.IntegerField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=15)),
                ('is_cpf_responsavel', models.IntegerField()),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('data_registro', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('motivo_desligamento', models.CharField(blank=True, max_length=300, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('valor_total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atividade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasFuncionamento',
            fields=[
                ('data_funcionamento', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'datas_funcionamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasLancamentosFrequenciasTurmas',
            fields=[
                ('id_data_lancamento', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'datas_lancamentos_frequencias_turmas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(max_length=100)),
                ('ementa_disciplina', models.CharField(blank=True, max_length=300, null=True)),
                ('id_curso', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id_falta', models.AutoField(primary_key=True, serialize=False)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'falta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaAluno',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('valor_nota', models.FloatField()),
            ],
            options={
                'db_table': 'nota_aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_periodo', models.CharField(max_length=45)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('is_atual', models.IntegerField(blank=True, null=True)),
                ('valor_liberacao_periodo', models.FloatField()),
                ('freq_min_aprov', models.IntegerField()),
                ('total_pts_periodo', models.IntegerField()),
                ('min_pts_aprov', models.IntegerField()),
                ('quantidade_alimentos', models.IntegerField()),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('nome_turma', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('sala', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TurmaAlunos',
            fields=[
                ('id_turma_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('id_pagamento', models.IntegerField()),
                ('aprovado', models.IntegerField(blank=True, null=True)),
                ('liberacao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'turma_alunos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TurmaAtividades',
            fields=[
                ('id_atividades_turma', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'turma_atividades',
                'managed': False,
            },
        ),
    ]
