# Generated by Django 2.2.3 on 2019-07-26 02:31

from django.db import migrations

# Péssima prática, mas valendo aqui pq não alteramos nosso DB
from mainapp.models import *


def muda_turmas(apps, schema_editor):
    def mudaturma(oldturma, newturma, nome):
        aluno = Aluno.objects.get(nome_aluno__icontains=nome)
        velho = TurmaAlunos.objects.get(
            id_aluno=aluno, id_turma__nome_turma=oldturma, id_turma__id_periodo__is_atual=1)
        novo = TurmaAlunos(id_aluno=aluno, id_turma=Turma.objects.get(nome_turma=newturma, id_periodo__is_atual=1),
                           id_pagamento=velho.id_pagamento, aprovado=velho.aprovado, liberacao=velho.liberacao)
        velho.delete()
        novo.save()

    mudaturma('INFC101', 'INFC102', 'MARIA VITÓRIA LEISTER LOPES')
    mudaturma('INA203', 'INA202', 'THIAGO AUGUSTO SANTOS')
    mudaturma('INB102', 'INB101', 'JOAO VICTOR PEREIRA DE SA')
    mudaturma('INE201','INE101','BRUNA LUIZA BATISTA BORGES')


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(muda_turmas),
    ]
