version: "3"

services:
  app:
    build: .
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    environment:
      SECRET_KEY: 'secret'
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_HOST: "19.17.11.8"
      DB_PORT: "3306"
    volumes:
      - .:/workspace
    links:
      - internaldb
    ports:
      - "80:8000"
    networks:
      static-network:
        ipv4_address: "19.17.11.7"
  internaldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_bin
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      static-network:
        ipv4_address: "19.17.11.8"
    volumes:
      - notas_data:/var/lib/mysql

networks:
  static-network:
    internal: false
    ipam:
      config:
        - subnet: "19.17.11.0/24"

volumes:
  notas_data: {}