version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    ports: 
      - "80:8000"
    volumes:
      - ..:/workspace
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig
    # Overrides default command so things don't shut down after the process ends.
    links: 
      - internaldb
  internaldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_bin
    restart: unless-stopped
    ports: 
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: "fechamentoincluir"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "lancamentoapp"
      MYSQL_PASSWORD: "gambigambi"
    networks:
      default: {}
      static-network:
        ipv4_address: "10.0.0.5"

networks:
  static-network:
    internal: false
    ipam:
      config:
        - subnet: "10.0.0.0/24"